services:
  
  # PHP container
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    depends_on:
      - mysql

  # Database container
  # use the same name as the name of the DB in .env DB_HOST
  mysql:
    image: mysql:latest
    ports:
      - 3307:3307
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_TCP_PORT=3307
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: ~