on:
  push:
    branches:
      - "main"
name: 🚀 Deploy Motustore app on push

env:
  DB_CONNECTION: mysql
  DB_DATABASE: motustore
  DB_USER: root
  DB_PASSWORD: root
  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Setup PHP with composer v2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer

    - name: Set up MySQL
      run: |
        sudo systemctl start mysql.service
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-progress

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: motustore
        DB_USERNAME: root
        DB_PASSWORD: root
        CACHE_DRIVER: array
        SESSION_DRIVER: array
        QUEUE_DRIVER: sync
        MAIL_MAILER: array
        MAIL_FROM_ADDRESS: service@udeh.ng
        MAIL_FROM_NAME: udeh.ng
        APP_KEY: base64:jqQ6xj54+p5qPcVYR8LqO4yGTpeLYWgbY4N3gOOoTrU=
        BCRYPT_ROUNDS: 4
        QUEUE_CONNECTION: sync
      run: php artisan test --stop-on-failure
  web-deploy:
    name: 🎉 Deploy motustore
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: udeh.ng
        username: ${{ secrets.udehng_ftp_username }}
        password: ${{ secrets.udehng_ftp_password }}
        server-dir: motutore.udeh.ng/
    # needs: tests